name: Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint_and_typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - name: npm ci
        run: npm ci
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: test
        run: npm run test --if-present
